// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.Repositories.TienDT.Models;

public partial class PaymentMethod
{
    public int MethodId { get; set; }

    public string MethodName { get; set; }

    public decimal? ProcessingFeePercent { get; set; }

    public bool? IsOnline { get; set; }

    public bool? IsActive { get; set; }
}