// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.Repositories.TienDT.Models;

public partial class StaffShift
{
    public int ShiftId { get; set; }

    public string ShiftName { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public decimal? HourlyRate { get; set; }

    public bool? IsActive { get; set; }
}