// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.Repositories.TienDT.Models;

public partial class StationAmenityMapping
{
    public int MappingId { get; set; }

    public int StationId { get; set; }

    public int AmenityId { get; set; }

    public bool? IsAvailable { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual StationAmenity Amenity { get; set; }

    public virtual Station Station { get; set; }
}