// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.Repositories.TienDT.Models;

public partial class Station
{
    public int StationId { get; set; }

    public string StationName { get; set; }

    public string Address { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public int TotalSlots { get; set; }

    public int AvailableSlots { get; set; }

    public bool IsOperational { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<RentalsTienDt> RentalsTienDts { get; set; } = new List<RentalsTienDt>();

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();

    public virtual ICollection<StationAmenityMapping> StationAmenityMappings { get; set; } = new List<StationAmenityMapping>();

    public virtual ICollection<VehicleStation> VehicleStations { get; set; } = new List<VehicleStation>();
}