// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.Repositories.TienDT.Models;

public partial class VehicleInspection
{
    public int InspectionId { get; set; }

    public int VehicleId { get; set; }

    public int StaffId { get; set; }

    public DateTime? InspectionDate { get; set; }

    public string ConditionNotes { get; set; }

    public bool? DamageReported { get; set; }

    public string PhotoUrls { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}