// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EVRental.Repositories.TienDT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;


namespace EVRental.Repositories.TienDT.DBContext;

public partial class FA25_PRN232_SE1717_G6_EVRentalContext : DbContext
{
    public FA25_PRN232_SE1717_G6_EVRentalContext()
    {
    }

    public FA25_PRN232_SE1717_G6_EVRentalContext(DbContextOptions<FA25_PRN232_SE1717_G6_EVRentalContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CustomerFeedback> CustomerFeedbacks { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<RentalStatusesTienDt> RentalStatusesTienDt { get; set; }

    public virtual DbSet<RentalsTienDt> RentalsTienDts { get; set; }

    public virtual DbSet<Staff> Staff { get; set; }

    public virtual DbSet<StaffShift> StaffShifts { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

    public virtual DbSet<StationAmenity> StationAmenities { get; set; }

    public virtual DbSet<StationAmenityMapping> StationAmenityMappings { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    public virtual DbSet<VehicleInspection> VehicleInspections { get; set; }

    public virtual DbSet<VehicleStation> VehicleStations { get; set; }

    public virtual DbSet<VehicleType> VehicleTypes { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=TIENTRONG\\TIENTRONG;Initial Catalog=FA25_PRN232_SE1717_G6_EVRental;Persist Security Info=True;User ID=sa;Password=123456;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CustomerFeedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__Customer__6A4BEDF649D8DF4C");

            entity.ToTable("CustomerFeedback");

            entity.HasIndex(e => e.Rating, "IX_CustomerFeedback_Rating");

            entity.Property(e => e.FeedbackId).HasColumnName("FeedbackID");
            entity.Property(e => e.Comments).HasMaxLength(1000);
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.RentalId).HasColumnName("RentalID");
            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");

            entity.HasOne(d => d.Rental).WithMany(p => p.CustomerFeedbacks)
                .HasForeignKey(d => d.RentalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerFeedback_RentalsTienDT_TienDT");

            entity.HasOne(d => d.UserAccount).WithMany(p => p.CustomerFeedbacks)
                .HasForeignKey(d => d.UserAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerFeedback_UserAccount_TienDT");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A58098DEEE2");

            entity.HasIndex(e => e.PaymentDate, "IX_Payments_PaymentDate");

            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.AdditionalFees)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsRefunded).HasDefaultValue(false);
            entity.Property(e => e.IsSuccessful).HasDefaultValue(false);
            entity.Property(e => e.PaymentAmount).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.PaymentDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PaymentType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RefundAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(12, 2)");
            entity.Property(e => e.RentalId).HasColumnName("RentalID");
            entity.Property(e => e.TransactionId)
                .HasMaxLength(100)
                .HasColumnName("TransactionID");
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");

            entity.HasOne(d => d.Rental).WithMany(p => p.Payments)
                .HasForeignKey(d => d.RentalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_RentalsTienDT_TienDT");

            entity.HasOne(d => d.UserAccount).WithMany(p => p.Payments)
                .HasForeignKey(d => d.UserAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_UserAccount_TienDT");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.MethodId).HasName("PK__PaymentM__FC681FB1F51B8B4D");

            entity.Property(e => e.MethodId).HasColumnName("MethodID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsOnline).HasDefaultValue(true);
            entity.Property(e => e.MethodName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProcessingFeePercent)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(5, 2)");
        });

        modelBuilder.Entity<RentalStatusesTienDt>(entity =>
        {
            entity.HasKey(e => e.RentalStatusTienDtid).HasName("PK__RentalSt__BED0F3E1396BAA9D");

            entity.ToTable("RentalStatusesTienDT");

            entity.Property(e => e.RentalStatusTienDtid).HasColumnName("RentalStatusTienDTID");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<RentalsTienDt>(entity =>
        {
            entity.HasKey(e => e.RentalTienDtid).HasName("PK__RentalsT__E6607316E1799D7E");

            entity.ToTable("RentalsTienDT");

            entity.HasIndex(e => e.RentalStatusTienDtid, "IX_RentalsTienDT_Status");

            entity.HasIndex(e => e.UserAccountId, "IX_RentalsTienDT_UserAccountID");

            entity.Property(e => e.RentalTienDtid).HasColumnName("RentalTienDTID");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsCompleted).HasDefaultValue(false);
            entity.Property(e => e.Note)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.RentalStatusTienDtid).HasColumnName("RentalStatusTienDTID");
            entity.Property(e => e.SecurityDeposit).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.StationId).HasColumnName("StationID");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");

            entity.HasOne(d => d.RentalStatusTienDt).WithMany(p => p.RentalsTienDts)
                .HasForeignKey(d => d.RentalStatusTienDtid)
                .HasConstraintName("FK_RentalsTienDT_RentalStatus_TienDT");

            entity.HasOne(d => d.Station).WithMany(p => p.RentalsTienDts)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RentalsTienDT_Stations_TienDT");

            entity.HasOne(d => d.UserAccount).WithMany(p => p.RentalsTienDts)
                .HasForeignKey(d => d.UserAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RentalsTienDT_UserAccount_TienDT");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.RentalsTienDts)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RentalsTienDT_Vehicles_TienDT");
        });

        modelBuilder.Entity<Staff>(entity =>
        {
            entity.HasKey(e => e.StaffId).HasName("PK__Staff__96D4AAF7F8240997");

            entity.HasIndex(e => e.StationId, "IX_Staff_StationID");

            entity.HasIndex(e => e.Email, "UQ__Staff__A9D10534E4242C44").IsUnique();

            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.AverageRating)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(3, 2)");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsOnDuty).HasDefaultValue(false);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Position)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StationId).HasColumnName("StationID");
            entity.Property(e => e.TotalTransactions).HasDefaultValue(0);
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Station).WithMany(p => p.Staff)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Staff_Stations_TienDT");
        });

        modelBuilder.Entity<StaffShift>(entity =>
        {
            entity.HasKey(e => e.ShiftId).HasName("PK__StaffShi__C0A838E12254C513");

            entity.Property(e => e.ShiftId).HasColumnName("ShiftID");
            entity.Property(e => e.HourlyRate).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ShiftName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Station>(entity =>
        {
            entity.HasKey(e => e.StationId).HasName("PK__Stations__E0D8A6DD850B17B3");

            entity.Property(e => e.StationId).HasColumnName("StationID");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsOperational).HasDefaultValue(true);
            entity.Property(e => e.Latitude).HasColumnType("decimal(10, 8)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(11, 8)");
            entity.Property(e => e.StationName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<StationAmenity>(entity =>
        {
            entity.HasKey(e => e.AmenityId).HasName("PK__StationA__842AF52B3BEA04A0");

            entity.Property(e => e.AmenityId).HasColumnName("AmenityID");
            entity.Property(e => e.AmenityName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IconUrl).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<StationAmenityMapping>(entity =>
        {
            entity.HasKey(e => e.MappingId).HasName("PK__StationA__8B5781BDA429CE91");

            entity.ToTable("StationAmenityMapping");

            entity.Property(e => e.MappingId).HasColumnName("MappingID");
            entity.Property(e => e.AmenityId).HasColumnName("AmenityID");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsAvailable).HasDefaultValue(true);
            entity.Property(e => e.StationId).HasColumnName("StationID");

            entity.HasOne(d => d.Amenity).WithMany(p => p.StationAmenityMappings)
                .HasForeignKey(d => d.AmenityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StationAmenityMapping_Amenities_TienDT");

            entity.HasOne(d => d.Station).WithMany(p => p.StationAmenityMappings)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StationAmenityMapping_Stations_TienDT");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("PK__Vehicles__476B54B21E733D11");

            entity.HasIndex(e => e.IsAvailable, "IX_Vehicles_IsAvailable");

            entity.HasIndex(e => e.VehicleTypeId, "IX_Vehicles_VehicleTypeID");

            entity.HasIndex(e => e.LicensePlate, "UQ__Vehicles__026BC15C527A8C06").IsUnique();

            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");
            entity.Property(e => e.BatteryCapacity).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CurrentBatteryLevel).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.HourlyRate).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsAvailable).HasDefaultValue(true);
            entity.Property(e => e.LicensePlate)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.VehicleModel)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");

            entity.HasOne(d => d.VehicleType).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.VehicleTypeId)
                .HasConstraintName("FK_Vehicles_VehicleTypes_TienDT");
        });

        modelBuilder.Entity<VehicleInspection>(entity =>
        {
            entity.HasKey(e => e.InspectionId).HasName("PK__VehicleI__30B2DC286634EC44");

            entity.Property(e => e.InspectionId).HasColumnName("InspectionID");
            entity.Property(e => e.ConditionNotes).HasMaxLength(1000);
            entity.Property(e => e.DamageReported).HasDefaultValue(false);
            entity.Property(e => e.InspectionDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.PhotoUrls).HasMaxLength(2000);
            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");

            entity.HasOne(d => d.Staff).WithMany(p => p.VehicleInspections)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VehicleInspections_Staff_TienDT");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.VehicleInspections)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VehicleInspections_Vehicles_TienDT");
        });

        modelBuilder.Entity<VehicleStation>(entity =>
        {
            entity.HasKey(e => e.VehicleStationId).HasName("PK__VehicleS__53C729B04580F500");

            entity.HasIndex(e => e.IsCurrentLocation, "IX_VehicleStations_CurrentLocation");

            entity.Property(e => e.VehicleStationId).HasColumnName("VehicleStationID");
            entity.Property(e => e.CheckInDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsCurrentLocation).HasDefaultValue(true);
            entity.Property(e => e.StationId).HasColumnName("StationID");
            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");

            entity.HasOne(d => d.Station).WithMany(p => p.VehicleStations)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VehicleStations_Stations_TienDT");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.VehicleStations)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VehicleStations_Vehicles_TienDT");
        });

        modelBuilder.Entity<VehicleType>(entity =>
        {
            entity.HasKey(e => e.VehicleTypeId).HasName("PK__VehicleT__9F449623451543C9");

            entity.Property(e => e.VehicleTypeId).HasColumnName("VehicleTypeID");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxSpeed).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}