// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.BlazorWebApp.TienDT.Models;

public partial class CustomerFeedback
{
    public int FeedbackId { get; set; }

    public int RentalId { get; set; }

    public int UserAccountId { get; set; }

    public int? Rating { get; set; }

    public string Comments { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual RentalsTienDt Rental { get; set; }

    public virtual SystemUserAccount UserAccount { get; set; }
}