// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.BlazorWebApp.TienDT.Models;
public partial class Payment
{
    public int PaymentId { get; set; }

    public int RentalId { get; set; }

    public int UserAccountId { get; set; }

    public decimal PaymentAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentType { get; set; }

    public string TransactionId { get; set; }

    public DateTime? PaymentDate { get; set; }

    public decimal? RefundAmount { get; set; }

    public decimal? AdditionalFees { get; set; }

    public bool? IsSuccessful { get; set; }

    public bool? IsRefunded { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual RentalsTienDt Rental { get; set; }

    public virtual SystemUserAccount UserAccount { get; set; }
}