// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EVRental.BlazorWebApp.TienDT.Models;
public partial class RentalStatusesTienDt
{
    [Key]
    public int RentalStatusTienDtid { get; set; }

    public string StatusName { get; set; }

    public string Description { get; set; }

    public int? DisplayOrder { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<RentalsTienDt> RentalsTienDts { get; set; } = new List<RentalsTienDt>();
}