// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EVRental.BlazorWebApp.TienDT.Models;
public partial class RentalsTienDt
{
    [Key]
    public int RentalTienDtid { get; set; }

    [Required(ErrorMessage = "User Account ID is required")]
    [Range(1, int.MaxValue, ErrorMessage = "Please select a valid User Account")]
    public int UserAccountId { get; set; }

    [Required(ErrorMessage = "Vehicle ID is required")]
    [Range(1, int.MaxValue, ErrorMessage = "Please select a valid Vehicle")]
    public int VehicleId { get; set; }

    [Required(ErrorMessage = "Station ID is required")]
    [Range(1, int.MaxValue, ErrorMessage = "Please select a valid Station")]
    public int StationId { get; set; }

    [Required(ErrorMessage = "Start Time is required")]
    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public DateTime? PlannedEndTime { get; set; }

    [Range(0, double.MaxValue, ErrorMessage = "Total Amount must be a positive value")]
    public decimal? TotalAmount { get; set; }

    [Required(ErrorMessage = "Security Deposit is required")]
    [Range(0, double.MaxValue, ErrorMessage = "Security Deposit must be a positive value")]
    public decimal SecurityDeposit { get; set; }

    [MaxLength(500, ErrorMessage = "Note cannot exceed 500 characters")]
    public string Note { get; set; }

    public int? RentalStatusTienDtid { get; set; }

    public bool? IsCompleted { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<CustomerFeedback> CustomerFeedbacks { get; set; } = new List<CustomerFeedback>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual RentalStatusesTienDt RentalStatusTienDt { get; set; }

    public virtual Station Station { get; set; }

    public virtual SystemUserAccount UserAccount { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}

public  partial class RentalsTienDtGraphQLResponse
{
    public List<RentalsTienDt> rentalsTienDts { get; set; }
}

public partial class RentalsTienDtGraphQLResponse
{
    public RentalsTienDt rrentalsTienDts { get; set; }
}
public partial class CreateGraphQLResponse 
{
    public int createRentalsTienDt { get; set; }

}


