// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.BlazorWebApp.TienDT.Models;
public partial class Staff
{
    public int StaffId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public int StationId { get; set; }

    public string Position { get; set; }

    public DateOnly HireDate { get; set; }

    public int? TotalTransactions { get; set; }

    public decimal? AverageRating { get; set; }

    public bool? IsOnDuty { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Station Station { get; set; }

    public virtual ICollection<VehicleInspection> VehicleInspections { get; set; } = new List<VehicleInspection>();
}