// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.BlazorWebApp.TienDT.Models;
public partial class StationAmenity
{
    public int AmenityId { get; set; }

    public string AmenityName { get; set; }

    public string Description { get; set; }

    public string IconUrl { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<StationAmenityMapping> StationAmenityMappings { get; set; } = new List<StationAmenityMapping>();
}