// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.BlazorWebApp.TienDT.Models;
public partial class Vehicle
{
    public int VehicleId { get; set; }

    public int? VehicleTypeId { get; set; }

    public string LicensePlate { get; set; }

    public string VehicleModel { get; set; }

    public decimal BatteryCapacity { get; set; }

    public decimal CurrentBatteryLevel { get; set; }

    public decimal HourlyRate { get; set; }

    public bool IsAvailable { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastMaintenanceDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<RentalsTienDt> RentalsTienDts { get; set; } = new List<RentalsTienDt>();

    public virtual ICollection<VehicleInspection> VehicleInspections { get; set; } = new List<VehicleInspection>();

    public virtual ICollection<VehicleStation> VehicleStations { get; set; } = new List<VehicleStation>();

    public virtual VehicleType VehicleType { get; set; }
}