// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVRental.BlazorWebApp.TienDT.Models;
public partial class VehicleStation
{
    public int VehicleStationId { get; set; }

    public int VehicleId { get; set; }

    public int StationId { get; set; }

    public DateTime? CheckInDate { get; set; }

    public DateTime? CheckOutDate { get; set; }

    public bool? IsCurrentLocation { get; set; }

    public virtual Station Station { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}